package ec.edu.espe.bethsabeboutique.view;

import com.mongodb.client.MongoClient;
import ec.edu.espe.bethsabeboutique.controller.ReportController;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author caeta
 */
public class PnlReportsMenu extends javax.swing.JFrame {
    ReportController reportController;
    String path;

    /**
     * Creates new form LoginPanel
     */
    public PnlReportsMenu() {
        reportController = new ReportController();
        initComponents();
        loadButtonListeners();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BtnReturn2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        BtnInventoryReport = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        BtnSalesReport = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setAlignmentX(0.0F);
        jPanel2.setAlignmentY(0.0F);
        jPanel2.setPreferredSize(new java.awt.Dimension(600, 400));
        jPanel2.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(226, 76, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 200));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(227, 227, 227));
        jLabel1.setText("Reportes");

        BtnReturn2.setBackground(new java.awt.Color(227, 227, 227));
        BtnReturn2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnReturn2.setForeground(new java.awt.Color(226, 76, 51));
        BtnReturn2.setText("Regresar");
        BtnReturn2.setBorderPainted(false);
        BtnReturn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnReturn2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnReturn2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135)
                .addComponent(jLabel1)
                .addContainerGap(209, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 2, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnReturn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(jPanel1);
        jPanel1.setBounds(0, 0, 600, 50);

        jPanel3.setBackground(new java.awt.Color(227, 227, 227));
        jPanel3.setFocusable(false);
        jPanel3.setRequestFocusEnabled(false);
        jPanel3.setVerifyInputWhenFocusTarget(false);

        BtnInventoryReport.setBackground(new java.awt.Color(227, 227, 227));
        BtnInventoryReport.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnInventoryReport.setForeground(new java.awt.Color(227, 227, 227));
        BtnInventoryReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/box.png"))); // NOI18N
        BtnInventoryReport.setAlignmentY(0.0F);
        BtnInventoryReport.setBorderPainted(false);
        BtnInventoryReport.setContentAreaFilled(false);
        BtnInventoryReport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnInventoryReport.setFocusable(false);
        BtnInventoryReport.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnInventoryReport.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/box.png"))); // NOI18N
        BtnInventoryReport.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/boxHover.png"))); // NOI18N
        BtnInventoryReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInventoryReportActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Reporte de inventario");

        BtnSalesReport.setBackground(new java.awt.Color(227, 227, 227));
        BtnSalesReport.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnSalesReport.setForeground(new java.awt.Color(227, 227, 227));
        BtnSalesReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sell.png"))); // NOI18N
        BtnSalesReport.setAlignmentY(0.0F);
        BtnSalesReport.setBorderPainted(false);
        BtnSalesReport.setContentAreaFilled(false);
        BtnSalesReport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnSalesReport.setFocusable(false);
        BtnSalesReport.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnSalesReport.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/sell.png"))); // NOI18N
        BtnSalesReport.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/sellHover.png"))); // NOI18N
        BtnSalesReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalesReportActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Reporte de ventas");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnInventoryReport, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(BtnSalesReport, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(98, 98, 98))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(97, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnSalesReport, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BtnInventoryReport, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(92, 92, 92))
        );

        jPanel2.add(jPanel3);
        jPanel3.setBounds(0, 50, 600, 350);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.getAccessibleContext().setAccessibleName("Login");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnInventoryReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInventoryReportActionPerformed
            
        
    }//GEN-LAST:event_BtnInventoryReportActionPerformed

    private void BtnSalesReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalesReportActionPerformed
        reportController.generateSalesReport("asd");
    }//GEN-LAST:event_BtnSalesReportActionPerformed

    private void BtnReturn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnReturn2ActionPerformed
        PnlMain pnlMain = new PnlMain();
        pnlMain.setVisible(true);
        pnlMain.setLocationRelativeTo(this);
        this.dispose();
    }//GEN-LAST:event_BtnReturn2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PnlReportsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PnlReportsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PnlReportsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PnlReportsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PnlReportsMenu().setVisible(true);
            }
        });
    }
    
    private void loadButtonListeners() {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        BtnInventoryReport.addActionListener(e -> {
            int result = fileChooser.showOpenDialog(this);

            if (result == JFileChooser.APPROVE_OPTION) {
                path = fileChooser.getSelectedFile().getPath();
                reportController.generateInventoryReport(path);
            } else if (result == JFileChooser.CANCEL_OPTION) {
                JOptionPane.showMessageDialog(this, "No se escogio ninguna carpeta", "Error", JOptionPane.ERROR_MESSAGE);
            }
        });
        
        BtnSalesReport.addActionListener(e -> {
            int result = fileChooser.showOpenDialog(this);

            if (result == JFileChooser.APPROVE_OPTION) {
                path = fileChooser.getSelectedFile().getPath();
                reportController.generateSalesReport(path);
            } else if (result == JFileChooser.CANCEL_OPTION) {
                JOptionPane.showMessageDialog(this, "No se escogio ninguna carpeta", "Error", JOptionPane.ERROR_MESSAGE);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnInventoryReport;
    private javax.swing.JButton BtnReturn2;
    private javax.swing.JButton BtnSalesReport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
