package ec.edu.espe.bethsabeboutique.view;

import com.mongodb.client.FindIterable;
import com.mongodb.client.MongoClient;
import ec.edu.espe.bethsabeboutique.controller.InventoryController;
import ec.edu.espe.bethsabeboutique.controller.SalesController;
import ec.edu.espe.bethsabeboutique.utils.BillsManager;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;
import org.bson.Document;
/**
 *
 * @author caeta
 */
public class PnlBillGraphics extends javax.swing.JPanel implements Printable{
    private MongoClient client;

    /**
     * Creates new form NewJPanel
     */
    public PnlBillGraphics() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblInventory = new javax.swing.JTable();
        LblProductAdded2 = new javax.swing.JLabel();
        LblProductAdded5 = new javax.swing.JLabel();
        LblProductAdded6 = new javax.swing.JLabel();
        LblProductAdded7 = new javax.swing.JLabel();
        LblProductAdded8 = new javax.swing.JLabel();
        LblProductAdded9 = new javax.swing.JLabel();
        txtIdNumber = new javax.swing.JTextField();
        txtCustomerName = new javax.swing.JTextField();
        txtCustomerAdress = new javax.swing.JTextField();
        txtCustomerEmail = new javax.swing.JTextField();
        txtCustomerPhoneNumber = new javax.swing.JTextField();
        LblProductAdded10 = new javax.swing.JLabel();
        LblTotalWithoutIva = new javax.swing.JLabel();
        LblProductAdded12 = new javax.swing.JLabel();
        LblProductAdded13 = new javax.swing.JLabel();
        LblIva = new javax.swing.JLabel();
        LblTotalWithIva = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        LblProductAdded4 = new javax.swing.JLabel();
        LblProductAdded3 = new javax.swing.JLabel();
        LblProductAdded1 = new javax.swing.JLabel();

        setLayout(null);

        jPanel1.setBackground(new java.awt.Color(226, 76, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 200));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(227, 227, 227));
        jLabel1.setText("FACTURA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel1)
                .addContainerGap(86, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        add(jPanel1);
        jPanel1.setBounds(0, 0, 370, 70);

        jPanel3.setBackground(new java.awt.Color(227, 227, 227));
        jPanel3.setFocusable(false);
        jPanel3.setRequestFocusEnabled(false);
        jPanel3.setVerifyInputWhenFocusTarget(false);

        TblInventory.setBackground(new java.awt.Color(227, 227, 227));
        TblInventory.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TblInventory.setForeground(new java.awt.Color(51, 51, 51));
        TblInventory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TblInventory.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TblInventory.setGridColor(new java.awt.Color(226, 76, 51));
        TblInventory.setName(""); // NOI18N
        TblInventory.setShowGrid(false);
        TblInventory.setShowVerticalLines(true);
        TblInventory.getTableHeader().setResizingAllowed(false);
        TblInventory.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(TblInventory);

        LblProductAdded2.setBackground(new java.awt.Color(0, 0, 0));
        LblProductAdded2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LblProductAdded2.setForeground(new java.awt.Color(102, 102, 102));
        LblProductAdded2.setText("Datos del Cliente: ");

        LblProductAdded5.setBackground(new java.awt.Color(0, 0, 0));
        LblProductAdded5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LblProductAdded5.setForeground(new java.awt.Color(102, 102, 102));
        LblProductAdded5.setText("Nombre: ");

        LblProductAdded6.setBackground(new java.awt.Color(0, 0, 0));
        LblProductAdded6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LblProductAdded6.setForeground(new java.awt.Color(102, 102, 102));
        LblProductAdded6.setText("Correo:");

        LblProductAdded7.setBackground(new java.awt.Color(0, 0, 0));
        LblProductAdded7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LblProductAdded7.setForeground(new java.awt.Color(102, 102, 102));
        LblProductAdded7.setText("Direccion:");

        LblProductAdded8.setBackground(new java.awt.Color(0, 0, 0));
        LblProductAdded8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LblProductAdded8.setForeground(new java.awt.Color(102, 102, 102));
        LblProductAdded8.setText("Número celular: ");

        LblProductAdded9.setBackground(new java.awt.Color(0, 0, 0));
        LblProductAdded9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LblProductAdded9.setForeground(new java.awt.Color(102, 102, 102));
        LblProductAdded9.setText("Número de cédula:");

        txtIdNumber.setBackground(new java.awt.Color(227, 227, 227));

        txtCustomerName.setBackground(new java.awt.Color(227, 227, 227));

        txtCustomerAdress.setBackground(new java.awt.Color(227, 227, 227));

        txtCustomerEmail.setBackground(new java.awt.Color(227, 227, 227));

        txtCustomerPhoneNumber.setBackground(new java.awt.Color(227, 227, 227));

        LblProductAdded10.setBackground(new java.awt.Color(0, 0, 0));
        LblProductAdded10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LblProductAdded10.setForeground(new java.awt.Color(102, 102, 102));
        LblProductAdded10.setText("Total sin iva (usd):");

        LblTotalWithoutIva.setBackground(new java.awt.Color(0, 0, 0));
        LblTotalWithoutIva.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LblTotalWithoutIva.setForeground(new java.awt.Color(102, 102, 102));
        LblTotalWithoutIva.setText("10");

        LblProductAdded12.setBackground(new java.awt.Color(0, 0, 0));
        LblProductAdded12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LblProductAdded12.setForeground(new java.awt.Color(102, 102, 102));
        LblProductAdded12.setText("iva (usd):");

        LblProductAdded13.setBackground(new java.awt.Color(0, 0, 0));
        LblProductAdded13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LblProductAdded13.setForeground(new java.awt.Color(102, 102, 102));
        LblProductAdded13.setText("Total (usd):");

        LblIva.setBackground(new java.awt.Color(0, 0, 0));
        LblIva.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LblIva.setForeground(new java.awt.Color(102, 102, 102));
        LblIva.setText("10");

        LblTotalWithIva.setBackground(new java.awt.Color(0, 0, 0));
        LblTotalWithIva.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LblTotalWithIva.setForeground(new java.awt.Color(102, 102, 102));
        LblTotalWithIva.setText("10");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(LblProductAdded2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(LblProductAdded9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtIdNumber))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LblProductAdded5)
                                    .addComponent(LblProductAdded7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCustomerAdress, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(LblProductAdded6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCustomerEmail))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(LblProductAdded8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCustomerPhoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(6, 344, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LblProductAdded13)
                            .addComponent(LblProductAdded10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(LblTotalWithoutIva)
                                .addGap(18, 18, 18)
                                .addComponent(LblProductAdded12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LblIva))
                            .addComponent(LblTotalWithIva))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(LblProductAdded2)
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblProductAdded9)
                    .addComponent(txtIdNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblProductAdded5)
                    .addComponent(txtCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblProductAdded6)
                    .addComponent(txtCustomerEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblProductAdded7)
                    .addComponent(txtCustomerAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblProductAdded8)
                    .addComponent(txtCustomerPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblProductAdded10)
                    .addComponent(LblTotalWithoutIva)
                    .addComponent(LblProductAdded12)
                    .addComponent(LblIva))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblProductAdded13)
                    .addComponent(LblTotalWithIva))
                .addGap(102, 102, 102))
        );

        add(jPanel3);
        jPanel3.setBounds(0, 70, 600, 490);

        jPanel2.setBackground(new java.awt.Color(227, 227, 227));

        LblProductAdded4.setBackground(new java.awt.Color(0, 0, 0));
        LblProductAdded4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LblProductAdded4.setForeground(new java.awt.Color(102, 102, 102));
        LblProductAdded4.setText("BethsabéBoutique");

        LblProductAdded3.setBackground(new java.awt.Color(0, 0, 0));
        LblProductAdded3.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        LblProductAdded3.setForeground(new java.awt.Color(102, 102, 102));
        LblProductAdded3.setText("Quito, San Rafael - Calle Tal");

        LblProductAdded1.setBackground(new java.awt.Color(0, 0, 0));
        LblProductAdded1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        LblProductAdded1.setForeground(new java.awt.Color(102, 102, 102));
        LblProductAdded1.setText("0983372690");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblProductAdded4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblProductAdded3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblProductAdded1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblProductAdded4)
                .addGap(0, 0, 0)
                .addComponent(LblProductAdded3)
                .addGap(0, 0, 0)
                .addComponent(LblProductAdded1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel2);
        jPanel2.setBounds(370, 0, 230, 70);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblIva;
    private javax.swing.JLabel LblProductAdded1;
    private javax.swing.JLabel LblProductAdded10;
    private javax.swing.JLabel LblProductAdded12;
    private javax.swing.JLabel LblProductAdded13;
    private javax.swing.JLabel LblProductAdded2;
    private javax.swing.JLabel LblProductAdded3;
    private javax.swing.JLabel LblProductAdded4;
    private javax.swing.JLabel LblProductAdded5;
    private javax.swing.JLabel LblProductAdded6;
    private javax.swing.JLabel LblProductAdded7;
    private javax.swing.JLabel LblProductAdded8;
    private javax.swing.JLabel LblProductAdded9;
    private javax.swing.JLabel LblTotalWithIva;
    private javax.swing.JLabel LblTotalWithoutIva;
    private javax.swing.JTable TblInventory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCustomerAdress;
    private javax.swing.JTextField txtCustomerEmail;
    private javax.swing.JTextField txtCustomerName;
    private javax.swing.JTextField txtCustomerPhoneNumber;
    private javax.swing.JTextField txtIdNumber;
    // End of variables declaration//GEN-END:variables
    
    public void loadTable() {
        SalesController salesController = new SalesController(client);
        FindIterable<Document> clientDresses;
        clientDresses = salesController.retrieveDocuments("Cart");
        DefaultTableModel model = new DefaultTableModel();
        String[] columns = {"id", "nombre", "precio", "cantidad"};
        model.setColumnIdentifiers(columns);
        
        String id, name, price, quantity;
        for(Document dress : clientDresses) {
            int index = 0;
            id = String.valueOf(dress.getInteger("id"));
            name = dress.getString("name");
            price = String.valueOf(dress.getDouble("price"));
            quantity = String.valueOf(dress.getInteger("quantity"));
            
            model.addRow(new Object[]{id, name, price, quantity});
            
            
            index++;  
        }
        TblInventory.setModel(model); 
        loadPrices();
    }
    
    public void loadPrices() {
        SalesController salesController = new SalesController(client);
        BillsManager billsManager = new BillsManager();
        float total = salesController.calculateTotal();
        float iva = billsManager.calculateIva(total, 12);
        float totalWithIva = Math.round((total+iva) * 100) / 100.0f;
        LblTotalWithoutIva.setText(String.valueOf(total));
        LblIva.setText(String.valueOf(iva));
        LblTotalWithIva.setText(String.valueOf(totalWithIva));
    }

    @Override
    public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
        if(pageIndex == 0) {
            Graphics2D graphics2D = (Graphics2D) graphics;
            graphics2D.translate(pageFormat.getImageableX(), pageFormat.getImageableY());
            printAll(graphics2D);
            return PAGE_EXISTS;
        }else {
            return NO_SUCH_PAGE;
        }
    }

    /**
     * @param client the client to set
     */
    public void setClient(MongoClient client) {
        this.client = client;
    }

    
}


